### ISSUE TITLE
2018.002.mods.xml

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#1]
Hi @cwulfman so as I start to go through the Plutarch volumes, I found my first issue.
For the file [2018.002.mods.xml](https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/monographs/2018.0002.mods.xml), it has 14 constituent volumes listed, although I know there are only seven physical volumes in this series.

Correspondingly most of the works are now listed as being in nonexistent volumes, or in the wrong volume. This current file ends Volume 1 at line 151, with only 5 works being in this volume, when in actuality there are fourteen works,and Volume 2 should have began at line 312 with work "regum et imperatorum apophthegmata"  but for some reason this is now in volume 3.  How is the volume data being generated exactly, because in none of the metadata anywhere for these works are there volume numbers beyond 7.

**Comment by AlisonBabeu** [comment]
In fact this seems to be a bug of some sort I"m wondering. The Loeb edition which is found at 2008.01.mods.xml does have fourteen volumes, but now the system seems to think that all of the Plutarch editions  have fourteen volumes. For example, [2008.005.mods.xml](https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/monographs/2018.0005.mods.xml) should have only five volumes.  It appears that in both the Teubner Greek edition and the Goodwin English edition that the system has just copied over the work data from the first Loeb edition (which does have fourteen volumes)

**Comment by cwulfman** [comment]
@AlisonBabeu you are right: I hand-compiled the "structural map" of the Loeb edition from the dirty OCR in the Internet Archives' copies and used that compilation as a template for the other editions, because the crucial information -- the manifestation of expressions of the various essays -- should carry over. There will, indeed, need to be structural shuffling around, as well as the addition of volume-specific metadata, like volume editors/translators, etc.

I'm operating under the assumption that the big thing we want to accomplish with this version of the catalog/bibliographic database is to make it possible for a user to find, say, expressions of "On the Education of Children" (or, expressions of same in English translations that are derived from a particular edition in Greek).

Shuffling around the structure of these big anthologies is going to be a bit of a pain, no question about it. Now, it may be that we don't really need all that detailed structure: it would be enough to say, for example, that an edition of the Moralia contains all of those essays, in a flat unstructured list of constituents. I can easily flatten the non-Loeb editions out for now -- that would be preferable to the current mis-structuring.

**Comment by AlisonBabeu** [comment]
hi @cwulfman, yes I agree that the most important part of the current project is to make it easier to find all the expressions of a work across languages. I would definitely flatten out the non-Loeb editions for the moment, it would be better to have no specific volume metadata, rather than incorrect data, which got me very confused as I started looking through the sample Moralia edition records.
