### ISSUE TITLE
Livy: ctsurns for individual books of ab urbe condita?

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#10]
In catalog pending, there are gazillions of editions of Livy, some in two volumes, some in fourteen, etc. At least some of them overlap with records that are already in the catalog.

How are you handling references to individual books, if at all?

**Comment by AlisonBabeu** [comment]
Who is this Livy of whom you speak?

**Comment by cwulfman** [comment]
First of all, what are *you* doing online on a Friday night??? 😄 

I'm talking about all the editions of _ab urbe condita_. Wallowing in classical ignorance here....

**Comment by AlisonBabeu** [comment]
I'm working because some other person decided to open an issue at 6:30 on a Friday. Truly barbaric.

And to be fair there are precisely seven editions of Livy, not a gazillion. These are all multi-volume holdovers of the old format, so in fact all of these volumes are indeed currently in the Perseus catalog.
The references to individual books were being contained typically within the ` <mods:tableOfContents>Books I and II</mods:tableOfContents>` for each individual MODS record.

**Comment by cwulfman** [comment]
My apologies for being chronologically agnostic....

So perhaps the path to pursue is more nuanced than I'd originally imagined: you and I simply (!) encode MODS records for those seven editions.  The more interesting angle, and one we might drag Matteo (and even Monica) into, is the granularity of CTS representation. At this point, I'm grappling with what it means to interleave manifestation-level, structural data (i.e., volumes) with more abstract constructs, like books of the _ab urbe condita_.

But definitely enough for a Friday night, even for me!

**Comment by cwulfman** [comment]
This is a bit of a mess, for at least two reasons: (1) Livy's _ab urbe condita_ has a single CTS urn (urn:cts:latinLit:phi0914.phi001), but (most of) the editions in the catalog contain subsets of the work: in some cases a few books, in other cases (esp. relating to the Punic War) excerpts from books. So it is not correct to say that these editions are manifestations of expressions of phi0914.001.  What are the CTS urns for individual books of Livy's history of Rome?

The second problem is overlap among editions in the catalog and catalog_pending. What is the difference between phi0914.phi001.opp-eng2 and phi0914.phi001.opp-eng17, and the corresponding  opp-lat2 and opp-lat28?

**Comment by AlisonBabeu** [comment]
I think it it correct to say that all these editions are manifestations of expressions of phi914.phi001. For many longer works such as Livy's Ab Urbe Condita, there are editions that contain only parts of the work.

There is overlap between editions in the catalog and catalog pending, because these multi-volume modsCollection records are meant to replace a number of editions already in the catalog.  I hadn't finished concatenating all of the multi-volume editions at the time of the last update in spring 2016.  
So in this case phi0914.phi001.opp-eng17 (a record for the entire Loeb edition of Livy) now includes the single volume described in phi0914.phi001.opp-eng2, plus several others. This might be easier to explain via Hangout later today.

**Comment by cwulfman** [comment]
@AlisonBabeu attached is a draft of MODS records for the six editions of Livy in catalog_pending. I've assembled them by looking at the original records in Catalog Pending and consulting Worldcat, Google Books, Hathi, Internet Archive, etc.

These are spare -- for each edition I've tried to bring over the metadata common to each volume and then create a structure of constituents corresponding the volumes of the edition and the books of Livy they contain. There are some issues with the Teubner edition (opp-lat33) that we should talk about: there are actually two editions here, the first edited by Weissenborn and the second, revised edition by Müller. They are conflated in the various digital archives.

At any rate, take a look when you can.  As part of the migration of the already-published catalog data, we'll want to revise the records for Livy to match these.

[ab_urbe_condita.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2023582/ab_urbe_condita.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
I will take a look at these tonight. One hopeful help is that I deleted all the original MODS records in catalog_data when I created these new MODS collection records in catalog_pending so there shouldn't be any duplication between them.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman. I hate to say this but I'm kind of confused about this approach because it seems to me so much of what we are hoping to do is to have less XML not more XML for these multi-volume works, and by having a separate   `<relatedItem` type="constituent" `otherType="work">` and   `<relatedItem` type="constituent" ``otherType="expression">` for each book you end up having to page through 27 work/expression statements before you get to volume 2 (of the same edition of Livy)

Perhaps might it be better to do the following and try to capture all the books in one statement:
```xml
        <relatedItem type="constituent" otherType="work">
                    <identifier type="ctsurn">urn:cts:latinLit:phi0914.phi001:1:27</identifier>
                    <relatedItem type="constituent" otherType="expression">
                        <identifier type="ctsurn"
                            >urn:cts:latinLit:phi0914.phi001:26.opp.eng7</identifier>
                    </relatedItem>
                </relatedItem>
            </relatedItem>
```

Also, where has all the other metadata for these multi-volumes gone at this point. There are no publication dates, online links or any of the other edition information. I apologize if I'm missing something but I'm not understanding how this new structural format will live along side all of the other information in the MODS record. Will the other metadata go to some separate manifestation level record?

**Comment by cwulfman** [comment]
Have you looked at the revisions I made yesterday, to conform with the new scheme we've been discussing in issue #11 ?

**Comment by AlisonBabeu** [comment]
I looked only at the Livy files attached above.

**Comment by cwulfman** [comment]
https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/singletons.mods.xml

**Comment by AlisonBabeu** [comment]
This is the MODS record I've being working through in the last few days,
but the file I am working with was last updated April 20th, so I'm still
not understanding
what you mean about recent revisions.

**Comment by cwulfman** [comment]
Damn – sorry about that!  It’s in a sub-folder for the catalog-pending records:

https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/from_catalog_pending/singletons.mods.xml

**Comment by AlisonBabeu** [comment]
That is OK. No worries for the moment. I think I will stick with the two
large files for the next few days since I"ve found  more than enough to
talk about in those for meeting
next Wednesday.  Enjoy the long weekend.

**Comment by cwulfman** [comment]
Ok – but do realize that those files are now out of date because they don’t use the work/expression/structure method we’ve been discussing the past few days. If we do decide to go this simplified route, I’ll have to do some automatic conversion.

Enjoy the weekend as well,

--C

**Comment by AlisonBabeu** [comment]
Quick question @cwulfman what is the nature/purpose of the embedded.mods.xml file, it seems to contain all of the Perseus reference works and a number of works found within larger volumes (but definitely not all of them), but it does not follow the same structure as the inverted.mods.xml file
