### ISSUE TITLE
Clarify fields in AAE spreadsheets

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#22]
In the AAE spreadsheets, do the VIAF ids all refer to authors, or are some of them ids for works?

**Comment by AlisonBabeu** [comment]
In about 90% of the cases I would say that the VIAF IDs refer to authors, but in some cases you are quite right, they are referring to a top level work page or "textgroup" I suppose, such as for individual poems in the Anthologia Latina (in Latin) and a number of other cases. Whenever there has been a VIAF URI for an anonymous work/textgroup as used by the PHI/TLG or other authority I have linked to it in the spreadsheet.

**Comment by cwulfman** [comment]
This makes the spreadsheets tricky to parse: I don't know if a row is for an author or for a work.

**Comment by AlisonBabeu** [comment]
You know at this point I'm ok with blurring the semantics for a bit, since this is part of the whole anonymous textgroup/author problem that we have in the catalog metadata overall. If we generate RDF for all the "author" row as authors, I can then identify that subset of RDF statements that represent textgroups (e.g. Anthologia Latina) rather than individuals if that makes sense.

**Comment by cwulfman** [comment]
Ok; thanks!
