### ISSUE TITLE
MODS records for Perseus editions

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#3]
I've just finished inverting/converting the MODS record for the Perrin edition/translation of _Plutarch's Lives_, including, as <relatedItem type='constituent' otherType='manifestation'> elements, URIs for the manifestations of the Perrin expressions (e.g., `urn:cts:greekLit:tlg0007.tlg065.opp-eng1-F3`).

A thing of beauty, if I do say so myself...

But there are also the Perseus "versions" (e.g. `urn:cts:greekLit:tlg0007.tlg065.perseus-eng1`), which are digital editions based on the Perrin. So I've created a parallel MODS record for the Perseus edition, with manifestation constituents that refer to the Perseus expressions (.e.g., `urn:cts:greekLit:tlg0007.tlg065.perseus-eng1-F3`).

Thoughts on this? It seems to me that it makes the catalog of manifestations more consistent -- why weren't the Perseus editions given their own MODS records before?

**Comment by AlisonBabeu** [comment]
Hi @cwulfman, I'm sorry again I didn't get a chance to look at this last week. So I have a few first thoughts:

1) Do we know yet why all the Perseus MODS records for individual Plutarch works within Perrin's Lives series were missed? A quick search of catalog_data for [Perrin, Perseus, Lives](https://github.com/PerseusDL/catalog_data/search?utf8=%E2%9C%93&q=Perrin+Perseus+Lives&type=) finds most of the missing records. For example, this [MODS record](https://github.com/PerseusDL/catalog_data/blob/fffbc6369e8b5fbf33f511f963c126e15a584828/mods/greekLit/tlg0007/tlg001/perseus-eng2/tlg0007.tlg001.perseus-eng2.mods1.xml) for the first work Theseus. 

2)  Why did the URLs for the various volume digital editions/e-books only show up only for volume 4, [lines 331-345](https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/monographs/plutarch-perseus.mods.xml#L331) and not for any of the other volumes?  I know there is a long term plan to copy individual publication information for each of the various volumes (online links, publication date information, possibly different editors) into the top level monograph record, but wondered why this bit of information showed up only for this volume?

At the same time, this re-aggregation work reminded me of the problems again the we had with the multi-volume work consolidation records in that the bibliographic information found at the start of the MODS records does not apply to the entire series but only to the first volume in that series (discussed in detail [here] (https://github.com/PerseusDL/catalog_data/issues/115).  I  still have not had a chance to go back through the multi-volumes and check on uniform titles as well as cleaning up volume level data, but I do think this is a serious issue we want to keep in mind so that we don't end up losing lots of data.

3) One thing I do like very much about this approach is how each work has its identifier in each record and then how the two manifestations are separated out by language and with unique manifestation level identifiers.  I can see that being very useful for aggregation of expression level information in the long run. I was also wondering at what level will the page level and the individual page links live for these various manifestations.  I"m trying to visualize what an expression level MODS record vs. a manifestation level MODS record might look like, but I guess I'm just getting ahead of us here..

I hope this is helpful in some remote way....

**Comment by cwulfman** [comment]
Interesting glitches! I'll look into them.

**Comment by cwulfman** [comment]
> 1.  Do we know yet why all the Perseus MODS records for individual Plutarch works within Perrin's Lives series were missed? A quick search of catalog_data for Perrin, Perseus, Lives finds most of the missing records. For example, this MODS record for the first work Theseus.

They are not in the Perrin record because that is the record for the printed edition. There is a separate MODS record for the Perseus encoding (plutarch-perseus.mods.xml). We need to work out a way of expressing the relationship between a printed edition and an encoding made from it.

> 2. Why did the URLs for the various volume digital editions/e-books only show up only for volume 4, lines 331-345 and not for any of the other volumes?

 Laziness: I used volume 4 more or less randomly as the base template, so those locations were ready to hand. 

> 3. I was also wondering at what level will the page level and the individual page links live for these various manifestations. 

Something for us to work out, of course, but I was imagining them being at the manifestation level. So for each manifestation, you could have pointers to the pages in the case of print, and some sort of fully-qualified URL/URN for the encoded editions.

**Comment by cwulfman** [comment]
@AlisonBabeu -- I wonder if we could return to this question? Should there be separate MODS records for Perseus encodings? I would say yes: they are new editions.

**Comment by AlisonBabeu** [comment]
Yes I think there should be, they are new editions and have a whole passel of legacy IDs I wouldn't want to lose.
